package com.example.marvelfandom

val marvelList: ArrayList<Marvel> = arrayListOf(
    Marvel(
        "Black Widow",
        "Natasha Romanova",
        "Originally Natasha’s gauntlets were more akin to bracelets (actually they are called bracelets by the KGB), and they had no offensive purpose. Like Spider-Man’s web-shooters, they generated a piece of string for her to swing around on (a \"Widow's Line\"), but unlike Spider-Man's web-shooters, they couldn’t tie up enemies or incapacitate.",
        "https://i.pinimg.com/564x/a2/f8/47/a2f847fb083e16bf0664e8da34ec2546.jpg",
        "Savage Avengers (Earth-616)",
        "The gauntlets were later improved upon by the Widow when she had a sudden inspiration to try and find a way to combine Spider-Man's powers with her own abilities. She decided to abandon her old costume and design a new one, as part of her \"rebirth.\" The newly designed gauntlets were described as shooting ropes and venom-sting bracelets.[2]\n" +
                "\n" +
                "It has been stated by Natasha that at times each gauntlet has weighed four kilos, leading her to almost blow her own hand off on one occasion and that the parts were difficult to replace especially while in the field.[3]\n" +
                "\n" +
                "The current gauntlets and the equipment it contains are upgraded and maintained by S.H.I.E.L.D. and the Widow, by being the owner, herself. Natalia Romanoff uses a number of special equipment contained in her gauntlets",
        39
    ),
    Marvel(
        "Dr. Strange",
        "Dr. Stephen Vincent Strange",
        "Dr. Stephen Strange, M.D.,[26] a.k.a. Doctor Strange, was the Sorcerer Supreme for Earth-616.[14] Strange was once a brilliant but arrogant Neurosurgeon, until a car accident crippled his hands.[11] When modern medicine failed him, he embarked on a journey to Kamar-Taj in Tibet, where he was trained by the Ancient One.[11] He healed his hands and learned more about Magic, eventually becoming a Master of the Mystic Arts.[14] He settled in the Sanctum Sanctorum in Greenwich Village, New York City, becoming the Earth's protector from any mystical threats.",
        "https://i.pinimg.com/564x/2c/ca/48/2cca487d463543a7fa6c605c345e2872.jpg",
        "Savage Avengers (Earth-616)",
        "After hearing rumors of the mystical Ancient One, Strange pawned his last possessions for a ticket to the East. Strange found the Ancient One's Tibetan palace, but the aged sorcerer refused to cure him, instead offering to teach him in mysticism. Strange refused but couldn't leave immediately due to a sudden blizzard. While staying for the duration of the storm, Strange witnessed the Ancient One's apprentice, Baron Mordo, secretly attack the teacher with mystically summoned skeletons, which the old man easily dispelled. Strange, his skepticism eroding, confronted Mordo about the treachery but Mordo responded with restraining spells that kept Strange from warning the Ancient One or attacking Mordo physically. Amazed by these displays of magic, Strange underwent a change of heart. Deciding that the only way to stop Mordo was to learn magic himself in order to challenge Mordo on his terms, Strange accepted the Ancient One's offer. Pleased by Strange's acceptance for unselfish reasons, the Ancient One removed the mystic restraints, explaining that he was well aware of Mordo\'s treachery but preferred to keep Mordo close by in order to control and possibly change him",
        61
    ),
    Marvel(
        "Spiderman",
        "Peter Benjamin Parker",
        "In 1962, with the success of the Fantastic Four, Marvel Comics editor and head writer Stan Lee was casting for a new superhero idea. He said the idea for Spider-Man arose from a surge in teenage demand for comic books and the desire to create a character with whom teens could identify.[15]: 1  As with Fantastic Four, Lee saw Spider-Man as an opportunity to \"get out of his system\" what he felt was missing in comic books.[16] In his autobiography, Lee cites the non-superhuman pulp magazine crime fighter the Spider as a great influence,[14]: 130 [17] and in a multitude of print and video interviews, Lee stated he was inspired by seeing a spider climb up a wall—adding in his autobiography that he has told that story so often he has become unsure of whether or not this is true.[note 1] Besides the name, the Spider was wanted by both the law and the criminal underworld (a defining theme of Spider-Man's early years) and had through years of ceaseless struggle developed a \"sixth sense\", which warns him of danger, the inspiration for Spider-Man's \"spider-sense\"",
        "https://i.pinimg.com/736x/a0/58/25/a05825b8e8d41f0daf638c9ca38e6842.jpg",
        "Threats and Menaces (Earth-616)",
        "Spider-Man is a superhero appearing in American comic books published by Marvel Comics. Created by writer-editor Stan Lee and artist Steve Ditko, he first appeared in the anthology comic book Amazing Fantasy #15 (August 1962) in the Silver Age of Comic Books. He has been featured in comic books, television shows, films, video games, novels, and plays.\n" +
                "\n" +
                "Spider-Man's secret identity is Peter Benjamin Parker. Initially, Peter was depicted as a teenage high-school student and an orphan raised by his Aunt May and Uncle Ben in New York City after his parents Richard and Mary Parker died in a plane crash. Lee and Ditko had the character deal with the struggles of adolescence and financial issues and gave him many supporting characters, such as Flash Thompson, J. Jonah Jameson, and Harry Osborn; romantic interests Gwen Stacy, Mary Jane Watson, and the Black Cat; and enemies such as the Green Goblin, Doctor Octopus, and Venom. In his origin story, Spider-Man gets his superhuman spider-powers and abilities after being bitten by a radioactive spider. These powers include superhuman strength, agility, reflexes, stamina, durability, coordination, and balance; clinging to surfaces and ceilings like a spider; and detecting danger with his precognition ability called \"spider-sense\". He builds wrist-mounted \"web-shooter\" devices that shoot artificial spider-webs of his own design, which he uses both for fighting and for web-swinging across the city. Peter Parker originally used his powers for his own personal gain, but after his Uncle Ben was killed by a thief that Peter could not stop, he began to use his powers to fight crime by becoming Spider-Man.",
        62
    ),
    Marvel(
        "Captain America",
        "Cpt. Steven Steve Rogers",
        "Cpt. Steven \"Steve\" Rogers a.k.a. Captain America,[50] the First Avenger,[29] was rejected by the U.S. Army during World War II due to numerous health problems. He ultimately volunteered for Project Rebirth where he received the Super-Soldier Serum developed by Dr. Abraham Erskine. The serum greatly enhanced his frail body to the peak of human physicality.[51] As the Sentinel of Liberty,[8] alongside his best friend Bucky Barnes[50] and the Invaders,[52] Rogers and others helped the Allies win the war, but not before he was lost at sea and frozen in ice in a form of suspended animation for decades. He was thawed out in the modern age to continue the battle alongside his new allies the Avengers.[53] Cap is loyal to no politician or government and instead upholds the \"timeless principles of freedom, equality, and justice of the American Dream\".[54]",
        "https://i.pinimg.com/236x/32/34/14/323414aa8d7e4046b9b60003f00e396d.jpg",
        "Avengers (Earth-616)",
        "Steve Rogers was born July 4, 1922,[55] to poor Irish immigrant parents, Sarah and Joseph Rogers.[56] Rogers grew up a frail youth during the Great Depression in New York City, New York. Little else is known about Rogers' early life other than the fact that a strong sense of duty, honor, and humility was instilled in him; perhaps due to his Irish Catholic upbringing. Rogers' father died when he was a child and his mother died from pneumonia later, when he was in his late teens.[57][58]\n" +
                "\n" +
                "Steve used to go to a school in the Lower East Side neighborhood. Among the people responsible for instilling the patriotic values in him were his civics teacher Edna Crosley, who taught that as an American it was their responsibility to protect the United States which gave more rights than any other country in the world to its citizens.[54]\n" +
                "\n" +
                "Becoming America's Super-Soldier\n" +
                "Horrified by newsreel footage of Nazis ransacking Europe and atrocities in Asia that the Empire of Japan committed in China and Korea, Rogers tried to enlist in the Army but was rejected as 4-F because of his frailty and sickness. Overhearing the boy's earnest plea to fight for his country, General Chester Phillips, of the US Army, offered Rogers the opportunity to take part in a top-secret performance-enhancing experiment called Operation Rebirth.[59]",
        84
    ),
    Marvel(
        "Thor",
        "Thor Odinson",
        "Thor is the God of Thunder,[59] a member of the race known as the Asgardians, a group of humanoid beings from the pocket dimension of Asgard,[60] the Realm Eternal.[61] Thor is the son of Odin, the All-Father and King of Asgard.[62] He was worshiped by the humans known as Vikings and became part of Norse mythology.[63] Armed with his enchanted Uru hammer Mjolnir, which helps him to channel his godly energies, he became the mightiest warrior in the Ten Realms. When his irresponsible and impetuous behavior became too much, Odin sent him to Midgard (more commonly known as Earth) as a disabled mortal medical student named Donald Blake, stripped of his memory. After learning humility, he regained his memory as well as his godly powers.[64][11] Thor went on to become a champion for Midgard as well as one of the founding members of the Avengers, \"Earth's Mightiest Heroes\".[65]",
        "https://i.pinimg.com/564x/4a/aa/77/4aaa7759aaaf34a7a17e688719002721.jpg",
        "Heralds of Galactus (Earth-616)",
        "Thor is the blood-son of Odin, All-Father of the Asgardians, and Jord, who was also known as Gaea, the earth-goddess who was one of the Elder Gods.[2] Odin claimed that he sought to father a son whose power would derive from both Asgard and Midgard (as the Earth realm is called by Asgardians), and hence he sought to mate with Jord. Odin created a cave in Norway where Jord gave birth to Thor.[66] Months after the infant Thor was weaned, Odin brought him to Asgard to be raised. Odin's wife, the goddess Frigga, acted as Thor's mother from that time onward, and for many years Thor believed her to be his birthmother. Not until many centuries later did Thor learn the purported truth that Jord was his birth mother,[67] though the Phoenix has asserted that Odin had lied about Thor's parentage and that it was his birth mother through Firehair, an ancient human mutant and avatar of the Phoenix Force,[41] claiming that Gaea was a lie to ensure that Thor would dedicate himself to protecting the Earth.[2] In truth, Gaea was Thor's birth mother, with the Phoenix acting as her midwife, but when the newborn Thor was assassinated by King Laufey the Phoenix resurrected him, leaving him permanently imbued with some of her power.[47]\n" +
                "\n" +
                "Ragnarok Cycle\n" +
                "The Ragnarok cycle created numerous versions of Thor's origin story, and the fact that Asgard was a place of myth did not help matters when trying to keep track of all of the different stories and personalized descriptions of events. One such story came from the severed eye of Odin, which grew to great size, achieved sentience, and told Thor of another Thor who had existed before the current Thor's birth. This previous Thor was also the son of Odin but had red hair, not blond hair like the current Thor. Thor was said in myth to have killed the Midgard Serpent, and to have been killed himself by the dying monster's venom, at Ragnarok, the destruction of a previous version of Asgard. Odin himself was killed, but a new Odin appeared in the place of several gods who survived Ragnarok, and it was this new Odin who fathered the current version of Thor. It is uncertain whether a true picture of Thor's origin will ever be told.[68]",
        74
    ),
    Marvel(
        "Loki",
        "Loki Laufeyson",
        "Before dying at the hands of the Void during the Siege on Asgard, the Trickster God Loki laid schemes to break free from the chains of destiny, manipulating Hela into taking his name out of the Book of Hel, allowing himself to be reborn instead of truly dying, and return as a completely new Loki, free of the weight of his past.[12]",
        "https://i.pinimg.com/564x/da/ff/46/daff467b4d9b9d978d191bccce6884dd.jpg",
        "Cabal (Dark Illuminati) (Earth-616)",
        "Beginning as Ikol\n" +
                "When he was trying to find the motive of his past incarnation for his sacrifice at the hands of the Void, the new Kid Loki found himself transported to a hidden chamber where he encountered an echo of his elder self. The spirit revealed the elder Loki desired to have a new start, a fresh page with fresh ink to write a free future. The echo had come to help the Kid Loki guard the Nine Realms through upcoming hard times, \"because a trickster is naught without a playground.\" Kid Loki reduced his elder self into the form of a magpie, condemned to a lifetime as \"Ikol,\" his minion and his opposite.[12] Determined not to become like his past self, Kid Loki went on several adventures to gain Thor's and everyone else's trust and affection. These adventures included hiding the World's Heart so Galactus would give up his war against Asgard, helping save Midgard from the War of the Serpent,[23] bringing Thor back from the dead by being the only person to remember him, helping Daimon Hellstrom save people from Nightmare,[24] assisting in the war with the Manchester Gods,[25] and helping Thor and Leah, Hela's handmaiden and his best friend, against Surtur. However, Ikol appeared displeased with his new incarnation's desire to be his own person, as well as his new personality.[26]\n" +
                "\n",
        57
    ),
    Marvel(
        "Iron Man",
        "Anthony Edward / Tony Stark",
        "Tony Stark is a genius inventor and billionaire industrialist, who suits up in his armor of cutting-edge technology to become the super hero Iron Man. The adopted son of weapons manufacturer Howard Stark,[46] Tony inherited his family's company at a young age following his parents' death.[47] While overseeing a manufacturing plant in a foreign country, Stark was kidnapped by local terrorists. Instead of giving in to his captors' demands to build weapons for them, Stark created a powerful suit of armor for himself to escape.[48] Returning to America, Stark further upgraded the armor and put his vast resources and intellect to use for the betterment of the world as Iron Man,[49][50] also quickly giving up weapons manufacturing, having experienced first-hand the horrors of war.[51]",
        "https://i.pinimg.com/564x/4a/42/e8/4a42e8ae030a7c4ae59e241052c5cf6b.jpg",
        "Avengers (Earth-616)",
        "Tony kept his alter-ego a secret for most of his career, juggling his responsibilities as head of Stark Industries while becoming a key player in the superhuman community as Iron Man and founding the world's premier super hero team, the Avengers.[52] Over the years, Stark has faced numerous enemies, such as the Mandarin, Justin Hammer, Iron Monger, and the Titanium Man, as well as many personal demons, most notably his addiction to alcohol.[53] For many years, Tony covered for his alter-ego by claiming that Iron Man was his anonymous bodyguard, but Tony eventually brought his dual identity to the public light.[54]\n" +
                "\n" +
                "Recently, Iron Man was backed into a corner by the anti-mutant industrialist Feilong, who took advantage of Tony divesting himself from his company, Stark Unlimited,[55] to acquire it and repurpose the Iron Man technology into mutant-hunting Stark Sentinels as part of his plans, alongside the think tank Orchis, to persecute mutantkind.[56] Designing a new stealth armor to operate from the shadows,[57] Iron Man joined forces with mutant telepath Emma Frost,[58] working as part of the Hellfire Club on the counter-offensive against Orchis and their global anti-mutant regime.[59]",
        62
    ),
    Marvel(
        "Hulk",
        "Dr. Robert Bruce Banner",
        "Dr. Robert Bruce Banner, Ph.D.[4] a.k.a. the Hulk is an American theoretical physicist, famed for his work in the fields of nuclear physics and gamma radiation.[63] He was recruited by General Thaddeus E. \"Thunderbolt\" Ross and the U.S. Army to develop the first Gamma Bomb. During its first live test he was bombarded with a massive dose of gamma rays while saving Rick Jones, a kid who had made his way onto the test site. He was mutated into a green behemoth, the living personification of rage, fueled by pure physical strength and would come to be known as the near mindless \"Incredible Hulk\". Fearful of the damage that Hulk could inflict, as well as fleeing from the military, he went on the run.[64]",
        "https://i.pinimg.com/564x/38/f3/1e/38f31e43f9c0502485927a3b86553dd7.jpg",
        "Cosmic Avengers (Earth-616)",
        "In the years that followed, Bruce became a loner, occasionally joining together with other heroes but more often struggling to be left alone. He was a founding member of the Avengers, \"Earth's Mightiest Heroes\", as well as the group of outsider heroes known as the Defenders, but would not remain with either group for long.[37][65] Over the years, the Hulk's personality changed drastically, owing to Banner's undiagnosed dissociative identity disorder. At times intelligent, other times savage, the one constant was his quest for solitude and peace in a world that would not leave him alone.[64] Robert Bruce Banner is the son of Dr. Brian Banner, an atomic physicist, and his wife Rebecca. Although Rebecca deeply loved Bruce, who returned her affection, Brian hated Bruce, and was driven by an insane jealousy of Bruce for being an object of Rebecca's love. Further, Brian believed that his radiation work had altered his DNA and given him a mutant son.[4] These factors led to Brian abusing Bruce physically. One of the people who helped Bruce cope with Brian's tantrums was his paternal cousin Jennifer Walters, with whom Bruce used to spend summers in the public library reading for hours, losing themselves to books.[66]\n" +
                "\n" +
                "Bruce's life reached a turning point when Brian murdered Rebecca, and he was placed in a mental hospital. After that, Bruce was raised by his aunt and father's sister, Susan Banner, who understood his great pain and rage over his childhood sufferings. Susan raised Bruce with love and care, as if he were her own child. Susan never wanted to deal with her brother after what he had done to Bruce and Rebecca. Bruce, grew up as a highly withdrawn, intellectually gifted youth, in fact, a child prodigy.[67] His father's abuse caused Bruce to start to develop dissociative identity disorder which would go undiagnosed for years, partly due to the fact his D.I.D. was suppressed.[68]",
        62
    ),
    Marvel(
        "Groot",
        "Groot",
        "Groot was a Flora colossi from Planet X, the capital of the Branchworlds, five gardens of suns and planets created by the Gardener.[10] Groot and his fellow Flora colossi, Tweeg and Gleef, were raised by their parents and the Arbor Masters, who served as teachers, protectors and monarchs. They learned through photosyntesis, as sunrise transmited the collected consciousness of generations of Arbor Masters into Groot and his peers.[11] Growing in the rebuild environment, Groot did not get along with his fellow saplings, instead preferring the company of the \"Maintenance Mammals\" who the other saplings treated with prejudice.[12] Living in the Herbaceous Habitats, these small animals and living fungi maintained the root system and the drainage, ran the Mycelium engine room, broke down compost and converted it into energy for the trees, and did the bidding of the Arbor Masters. Although they felt oppressed, only Groot ever took notice of this, and campaigned for their rights, an act that inspired them to form an Undergrowth Resistance.[3] In turn, Groot also felt alienated from the adults of his species, as they went to different worlds to conquer them or kidnap test subjects, such as Groot XXCVII did.[12]",
        "https://i.pinimg.com/564x/30/7d/d2/307dd2e912df8f4aea0ad35f2dfe2fc7.jpg",
        "Guardians of the Galaxy (Earth-616)",
        "When Groot was still a kid, he walked alongside his father when he witnessed the arrival of a Leviathon called Furnax, who burned 80,000 square kilometers of forest and everything inside it in a single night, shoving anything that couldn't run away into its own body to use as fuel. Groot and his father surveyed the damage, and Groot was traumatized.[8]\n" +
                "\n" +
                "The first Flora Colossi, matriarch elder Granopy, told Groot and his peer stories and to never go into the Deadwoods. However, one day, out of curiosity, Groot, Tweeg and Gleef checked the forbidden area, only to be captured by the criminal organization known as the Spoilers. They were taken off world to an outpost of the Spoilers on another planet, where they were freed by Private Mar-Vell of the Kree Starforce. Although wary of Mar-Vell at first, Groot and his friends got along with him as the Kree Private and his superior Captain So-Lar went to Planet X to see possible Spoiler activity there.[13]\n" +
                "\n" +
                "However, they were ambushed by the Spoilers' Chainsaurs which killed So-Lar, while Groot, Gleef, Tweeg and Mar-Vell were saved by the intervention of the Centaurian hunter Yondar. Going to safer place, Yondar explained to the three little Flora colossi that she had a personal vendetta against the Spoilers and had arrived to Planet X after finding a piece belonging to a Flora colossi. She further elaborated that the motionless Flora colossi were already silent when she came and was unsure why they refused to speak, though she believed they were afraid and ashamed of the Spoilers' presence in their world. Telling the group that the Spoilers were stationed in the Deadwoods, Mar-Vell decided to attack it to prevent further worlds from falling to their hands. Groot and his fellow saplings accompanied Mar-Vell and Yondar into the Deadwoods, but again were attacked by the Chainsaurs, resulting in the capture of Mar-Vell, Tweeg and Gleef, while Groot and Yondar barely managed to escape.[14]",
        17
    ),
    Marvel(
        "Rocket Raccoon",
        "Rocket Raccoon",
        "Rocket Raccoon is a genetically and cybernetically enhanced raccoon[12][3][13] turned freelance mercenary turned member of the Guardians of the Galaxy.[6] He is considered to have one of the best tactical minds in the galaxy.[6] He hails from Halfworld in the Keystone Quadrant where machines were able to turn animals into sentient beings.[14]",
        "https://images.squarespace-cdn.com/content/v1/5133bc80e4b0c6fb04dcd6c4/1700660187444-SL0CDW6ON55GNAD2JKS0/rocket_racoon_e27_web.jpg",
        "Guardians of the Galaxy (Earth-616)",
        "Somewhere in the black holes of Sirius Major there lived a young boy by the name of Rocket Raccoon. Possibly snatched from Earth,[12] he was used by a group of alien humanoids as a therapy animal for the inmates in the Halfworld Asylum for the Criminally Insane.[15] A young raccoon[12][3][13] with no intelligence, Rocket was used as the service animal for a patient named Khevix, a war veteran with a mouth like a sailor and bad dreams. He liked Rocket to sit in his lap while they watched dumb old war movies. He was good to Rocket — the last one to ever be.[16] When Rocket turned one-year old, he was granted a ranger uniform by his friends Pyko, Lylla, and her uncle Wal Rus, but the bunny Blackjack O'Hare stole the birthday cake so that he, Dyvyne and Jakes could eat it. Retrieving it was Ranger Rocket's first mission.[20] After this, Rocket helped Wal Rus replace his teeth for weaponized, mechanical prosthesis after he broke his original ones.[21]\n" +
                "\n" +
                "When Rocket was six years old, he was somehow spotted outside Halfworld, where he met Gamora, the most dangerous woman in the galaxy, and the two of them were captured by Badoons. They were rescued by Jesse Alexander and his Supernovas, and Rocket and Gamora formed a friendship with Jesse.[22]\n" +
                "\n" +
                "Over time, Lylla became Rocket's girlfriend and her uncle Wal Rus became Rocket's partner. When Rocket bought a ship for the two of them, Wal Rus wanted to name it Wailing Wal, but Lylla proposed Rakk 'n' Ruin, and Rocket liked the alliteration with his own name. Wal Rus was left playfully resentful about this, refusing to refer to the ship as belonging to the two of them. As they used the ship to travel Halfworld, Rocket became known as the fastest gun in the Quadrant. Once, the Hulk arrived to the planet,[23] but he experienced a \"comforting children's tale\" version of the world, presumably from being immersed in a virtual reality, perhaps even along with Rocket and his friends. Hulk was promptly sent back to Earth to prevent him from upsetting the status quo.[19]",
        42
    )
)
